# Generated by Django 3.1.5 on 2021-02-12 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва продукту')),
                ('slug', models.SlugField(unique=True)),
                ('run', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Пробіг')),
                ('years', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Рік випуску')),
                ('kpp', models.CharField(max_length=255, verbose_name='КПП')),
                ('engine', models.CharField(max_length=255, verbose_name='Двигун')),
                ('plus', models.TextField(default='нема', max_length=255, verbose_name='Переваги')),
                ('minus', models.TextField(default='нема', max_length=255, verbose_name='Недоліки')),
                ('price', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Ціна')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва категорії')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ім`я')),
                ('phone', models.CharField(max_length=13, verbose_name='Номер телефону')),
                ('comment', models.TextField(blank=True, max_length=100, null=True, verbose_name='Коментар до замовлення')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва продукту')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(default='SOME STRING', upload_to='', verbose_name='Зображення')),
                ('services', models.TextField(max_length=700, verbose_name='В послугу входить')),
                ('price', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Ціна')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категорія')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва продукту')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(default='SOME STRING', upload_to='', verbose_name='Зображення')),
                ('reviews', models.TextField(max_length=700, verbose_name='Відгук')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.car', verbose_name='Авто')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категорія')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.order', verbose_name='Ім`я')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.services', verbose_name='Послуги')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('car', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категорія'),
        ),
        migrations.AddField(
            model_name='car',
            name='services',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.services', verbose_name='Послуги'),
        ),
    ]
