# Generated by Django 3.1.5 on 2021-02-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image2',
            field=models.ImageField(default='SOME STRING', upload_to='', verbose_name='Зображення2'),
        ),
    ]
