# Generated by Django 3.1.5 on 2021-02-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_car_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.AddField(
            model_name='car',
            name='image1',
            field=models.ImageField(default='SOME STRING', upload_to='', verbose_name='Зображення1'),
        ),
        migrations.AddField(
            model_name='car',
            name='image3',
            field=models.ImageField(default='SOME STRING', upload_to='', verbose_name='Зображення3'),
        ),
    ]
