# Generated by Django 3.1.5 on 2021-02-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210213_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image1',
            field=models.ImageField(default=5, upload_to='', verbose_name='Зображення1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='image2',
            field=models.ImageField(default=959, upload_to='', verbose_name='Зображення2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='image3',
            field=models.ImageField(default=1, upload_to='', verbose_name='Зображення3'),
            preserve_default=False,
        ),
    ]
