# Generated by Django 3.1.5 on 2021-02-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210215_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='images',
            field=models.ImageField(upload_to='', verbose_name='Головне зображення'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='images',
            field=models.ImageField(upload_to='', verbose_name='Головне зображення'),
        ),
        migrations.AlterField(
            model_name='services',
            name='images',
            field=models.ImageField(upload_to='', verbose_name='Головне зображення'),
        ),
    ]
