# Generated by Django 3.1.5 on 2021-02-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210215_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='services_desc',
            field=models.TextField(default=4554, max_length=255, verbose_name='Короткий опис послуги '),
            preserve_default=False,
        ),
    ]
