# Generated by Django 3.1.5 on 2021-02-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_services_services_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='images',
            field=models.ImageField(upload_to='', verbose_name='Зображення для сторінки послуг'),
        ),
    ]
